import os 
#
#os.system('python plotOnewPresc.py B2G')
#os.system('python plotOnewPresc.py SUSY')
#os.system('python plotOnewPresc.py EXO')
#os.system('python plotOnewPresc.py Higgs')
#os.system('python plotOnewPresc.py TOP')
#os.system('python plotOnewPresc.py BPH')
#os.system('python plotOnewPresc.py E_GAMMA')
#os.system('python plotOnewPresc.py Taus')
#os.system('python plotOnewPresc.py template')
#os.system('python plotOnewPresc.py SMP')
#os.system('python plotOnewPresc.py JET_MET')
#os.system('python plotOnewPresc.py BTV')
##os.system('python plotOnewPresc.py TSG')
#os.system('python plotOnewPresc.py All')
#

#os.system('python plotRatePerSampleOnevsTwo.py B2G')
#os.system('python plotRatePerSampleOnevsTwo.py SUSY')
#os.system('python plotRatePerSampleOnevsTwo.py EXO')
#os.system('python plotRatePerSampleOnevsTwo.py Higgs')
#os.system('python plotRatePerSampleOnevsTwo.py TOP')
#os.system('python plotRatePerSampleOnevsTwo.py BPH')
#os.system('python plotRatePerSampleOnevsTwo.py E_GAMMA')
#os.system('python plotRatePerSampleOnevsTwo.py Taus')
#os.system('python plotRatePerSampleOnevsTwo.py template')
#os.system('python plotRatePerSampleOnevsTwo.py SMP')
#os.system('python plotRatePerSampleOnevsTwo.py JET_MET')
#os.system('python plotRatePerSampleOnevsTwo.py BTV')
##os.system('python plotRatePerSampleOnevsTwo.py TSG')
os.system('python plotRatePerSampleOnevsTwo.py All')

#os.system('python plotOnevsTwowPresc.py B2G')
#os.system('python plotOnevsTwowPresc.py SUSY')
#os.system('python plotOnevsTwowPresc.py EXO')
#os.system('python plotOnevsTwowPresc.py Higgs')
#os.system('python plotOnevsTwowPresc.py TOP')
#os.system('python plotOnevsTwowPresc.py BPH')
#os.system('python plotOnevsTwowPresc.py E_GAMMA')
#os.system('python plotOnevsTwowPresc.py Taus')
##os.system('python plotOnevsTwowPresc.py template')
#os.system('python plotOnevsTwowPresc.py SMP')
#os.system('python plotOnevsTwowPresc.py JET_MET')
#os.system('python plotOnevsTwowPresc.py BTV')
##os.system('python plotOnevsTwowPresc.py TSG')
#os.system('python plotOnevsTwowPresc.py All')
#

