import os 

os.system('python plotOnevsTwo.py MET')
os.system('python plotOnevsTwo.py SingleElectron')
os.system('python plotOnevsTwo.py SingleMu')
os.system('python plotOnevsTwo.py HTMHT')
os.system('python plotOnevsTwo.py DoublePhoton')
os.system('python plotOnevsTwo.py DoubleMu')
os.system('python plotOnevsTwo.py SinglePhoton')
os.system('python plotOnevsTwo.py JetHT')
os.system('python plotOnevsTwo.py DoubleElectron')
os.system('python plotOnevsTwo.py PhotonHad')
os.system('python plotOnevsTwo.py MultiJet')
os.system('python plotOnevsTwo.py MuHad')
os.system('python plotOnevsTwo.py MuOnia')
os.system('python plotOnevsTwo.py BTag')
os.system('python plotOnevsTwo.py ElectronHad')
os.system('python plotOnevsTwo.py TauPlusX')
os.system('python plotOnevsTwo.py Tau')
os.system('python plotOnevsTwo.py BJetPlusX')
os.system('python plotOnevsTwo.py MuEG')

